### ISSUE TITLE
EllipsisType in temper-core requires Python 3.10

### ISSUE THREAD

**Issue by tjpalmer** [temperlang/temper#41]
Our py backend is no longer compatible with Python 3.8 because we use EllipsisType in temper-core. For example:

```
_____________________________________________ ERROR collecting tests/Averages/Arithmetic_mean/test_example.py ______________________________________________
ImportError while importing test module '/home/tom/projects/rosettacodes/temper.out/py/rosetta-code-examples/tests/Averages/Arithmetic_mean/test_example.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/Averages/Arithmetic_mean/test_example.py:3: in <module>
    from temper_core import list_get_or as list_get_or_233, int_to_float64 as int_to_float64_234, str_cat as str_cat_235, float64_to_string as float64_to_string_236
../temper-core/temper_core/__init__.py:11: in <module>
    from types import MappingProxyType, EllipsisType
E   ImportError: cannot import name 'EllipsisType' from 'types' (/usr/lib/python3.9/types.py)
```

**Comment by tjpalmer** [comment]
This has been fixed by reverting to `None` rather than `...` to indicate missing args. We might adjust plans again, but this gets us working on Python 3.8 again.
